// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { GenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Greeter } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: GreeterContractApi
 * @contractName: greeter
 * @contractVersion: 0.0.1
 * @authors: Scio Labs <hello@scio.xyz>
 * @language: ink! 5.0.0
 **/
export interface GreeterContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends GenericContractApi<Rv, ChainApi> {
  query: ContractQuery<ChainApi[Rv]>;
  tx: ContractTx<ChainApi[Rv]>;
  constructorQuery: ConstructorQuery<ChainApi[Rv]>;
  constructorTx: ConstructorTx<ChainApi[Rv], GreeterContractApi>;
  events: ContractEvents<ChainApi[Rv]>;
  storage: {
    root(): Promise<Greeter>;
    lazy(): WithLazyStorage<Greeter>;
  };

  types: {
    RootStorage: Greeter;
    LazyStorage: WithLazyStorage<Greeter>;
    LangError: InkPrimitivesLangError;
    ChainApi: ChainApi[Rv];
  };
}
