// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   *
   * @param {bigint} supply
   * @param {string | undefined} name
   * @param {string | undefined} symbol
   * @param {number} decimals
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      supply: bigint,
      name: string | undefined,
      symbol: string | undefined,
      decimals: number,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
