// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Psp22Token } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: Psp22ContractApi
 * @contractName: psp22
 * @contractVersion: 3.0.0
 * @authors: Cardinal
 * @language: ink! 6.0.0-alpha.3
 **/
export interface Psp22ContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<'ink'>;
  tx: ContractTx<'ink'>;
  constructorQuery: ConstructorQuery<'ink'>;
  constructorTx: ConstructorTx<Psp22ContractApi, 'ink'>;
  events: ContractEvents<'ink'>;
  storage: {
    root(): Promise<Psp22Token>;
    lazy(): WithLazyStorage<Psp22Token>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Psp22Token;
    LazyStorage: WithLazyStorage<Psp22Token>;
    LangError: InkPrimitivesLangError;
  };
}
