// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, BytesLike } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
  GenericContractEvents,
  GenericContractEvent,
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
} from 'dedot/contracts';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericConstructorQuery<ChainApi, Type> {
  /**
   * @param {ConstructorCallOptions} options
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>,
    Type
  >;
}
