// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   * @param {ConstructorCallOptions} options
   **/
  new: GenericConstructorQueryCall<
    (options?: ConstructorCallOptions) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
