// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, BytesLike } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
  GenericContractEvents,
  GenericContractEvent,
} from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractEvents<ChainApi, Type> {
  FallbackCalled: GenericContractEvent<
    'FallbackCalled',
    {
      /**
       * @indexed: true
       **/
      sender: H160;
      /**
       * @indexed: false
       **/
      value: bigint;
      /**
       * @indexed: false
       **/
      data: BytesLike;
    },
    Type
  >;

  Received: GenericContractEvent<
    'Received',
    {
      /**
       * @indexed: true
       **/
      sender: H160;
      /**
       * @indexed: false
       **/
      value: bigint;
    },
    Type
  >;
}
