// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {
  Updated: GenericContractEvent<
    'Updated',
    {
      /**
       * @indexed: true
       **/
      updater: H160;
      /**
       * @indexed: false
       **/
      newValue: bigint;
    },
    Type
  >;
}
