// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { SolGenericContractApi, SolRegistry } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

export interface StorageContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends SolGenericContractApi<ChainApi> {
  metadataType: 'sol';
  query: ContractQuery<'sol'>;
  tx: ContractTx<'sol'>;
  constructorQuery: ConstructorQuery<'sol'>;
  events: ContractEvents<'sol'>;
  constructorTx: ConstructorTx<StorageContractApi, 'sol'>;

  types: {
    ChainApi: ChainApi;
  };
}
