// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, BytesLike } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
  GenericContractEvents,
  GenericContractEvent,
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * @param {bigint} num
   * @param {ContractTxOptions} options
   **/
  store: GenericContractTxCall<
    ChainApi,
    (num: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
