// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  ContractSubmittableExtrinsic,
  ContractTxOptions,
  GenericContractTx,
  GenericContractTxCall,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * @param {bigint} num
   * @param {ContractTxOptions} options
   **/
  store: GenericContractTxCall<
    ChainApi,
    (num: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
