// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<Type extends MetadataType> extends GenericContractTx<Type> {
  /**
   * @param {bigint} num
   * @param {ContractTxOptions} options
   **/
  store: GenericContractTxCall<(num: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic, Type>;
}
