// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {}
