// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Flipper6 } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: Flipper6ContractApi
 * @contractName: flipper6
 * @contractVersion: 0.1.0
 * @authors: [your_name] <[your_email]>
 * @language: ink! 6.0.0-alpha
 **/
export interface Flipper6ContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<'ink'>;
  tx: ContractTx<'ink'>;
  constructorQuery: ConstructorQuery<'ink'>;
  constructorTx: ConstructorTx<Flipper6ContractApi, 'ink'>;
  events: ContractEvents<'ink'>;
  storage: {
    root(): Promise<Flipper6>;
    lazy(): WithLazyStorage<Flipper6>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Flipper6;
    LazyStorage: WithLazyStorage<Flipper6>;
    LangError: InkPrimitivesLangError;
  };
}
