// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { GenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Flipper6 } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: Flipper6ContractApi
 * @contractName: flipper6
 * @contractVersion: 0.1.0
 * @authors: [your_name] <[your_email]>
 * @language: ink! 6.0.0-alpha
 **/
export interface Flipper6ContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends GenericContractApi<Rv, ChainApi> {
  query: ContractQuery<ChainApi[Rv]>;
  tx: ContractTx<ChainApi[Rv]>;
  constructorQuery: ConstructorQuery<ChainApi[Rv]>;
  constructorTx: ConstructorTx<ChainApi[Rv], Flipper6ContractApi>;
  events: ContractEvents<ChainApi[Rv]>;
  storage: {
    root(): Promise<Flipper6>;
    lazy(): WithLazyStorage<Flipper6>;
  };

  types: {
    RootStorage: Flipper6;
    LazyStorage: WithLazyStorage<Flipper6>;
    LangError: InkPrimitivesLangError;
    ChainApi: ChainApi[Rv];
  };
}
