// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Greeter } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: GreeterContractApi
 * @contractName: greeter
 * @contractVersion: 0.0.1
 * @authors: Scio Labs <hello@scio.xyz>
 * @language: ink! 5.0.0
 **/
export interface GreeterContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<'ink'>;
  tx: ContractTx<'ink'>;
  constructorQuery: ConstructorQuery<'ink'>;
  constructorTx: ConstructorTx<GreeterContractApi, 'ink'>;
  events: ContractEvents<'ink'>;
  storage: {
    root(): Promise<Greeter>;
    lazy(): WithLazyStorage<Greeter>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Greeter;
    LazyStorage: WithLazyStorage<Greeter>;
    LangError: InkPrimitivesLangError;
  };
}
