// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  ConstructorCallOptions,
  ContractInstantiateResult,
  GenericConstructorCallResult,
  GenericConstructorQuery,
  GenericConstructorQueryCall,
} from 'dedot/contracts';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi> extends GenericConstructorQuery<ChainApi> {
  /**
   *
   * @param {bigint} supply
   * @param {string | undefined} name
   * @param {string | undefined} symbol
   * @param {number} decimals
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      supply: bigint,
      name: string | undefined,
      symbol: string | undefined,
      decimals: number,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>
  >;
}
