// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, Hash } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError, FlipperFlipperError } from './types.js';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   * Creates a new flipper smart contract initialized with the given value.
   *
   * @param {boolean} initValue
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      initValue: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;

  /**
   * Creates a new flipper smart contract initialized to `false`.
   *
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x61ef7e3e
   **/
  newDefault: GenericConstructorQueryCall<
    (options?: ConstructorCallOptions) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;

  /**
   * Creates a new flipper smart contract with the value being calculate using provided seed.
   *
   * @param {Hash} seed
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x6d4cae81
   **/
  fromSeed: GenericConstructorQueryCall<
    (
      seed: Hash,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<Result<[], FlipperFlipperError>, ContractInstantiateResult>>,
    Type
  >;
}
