// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi> extends GenericContractEvents<ChainApi> {
  /**
   * Emitted when the flip function is called.
   *
   *
   **/
  Flipped: GenericContractEvent<
    'Flipped',
    {
      /**
       * The previous state of the flip.
       *
       * @indexed: false
       **/
      old: boolean;
      /**
       * The new state of the flip.
       *
       * @indexed: false
       **/
      new: boolean;
    }
  >;
}
