// Generated by dedot cli
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ContractEvents<ChainApi extends GenericSubstrateApi> extends GenericContractEvents<ChainApi> {}
