// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * Returns the current value of `message`.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x052cda08
   **/
  greet: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<string, ContractCallResult>>,
    Type
  >;

  /**
   * Sets `message` to the given value.
   *
   * @param {string} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x1fe7426f
   **/
  setMessage: GenericContractQueryCall<
    (newValue: string, options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;
}
