// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorTx,
  SolGenericContractApi,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends SolGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * @param {boolean} init_value
   * @param {ConstructorTxOptions} options
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      init_value: boolean,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
