// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorTx,
  SolGenericContractApi,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorTx<
  ContractApi extends SolGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<Type> {
  /**
   * @param {boolean} init_value
   * @param {ConstructorTxOptions} options
   **/
  new: GenericConstructorTxCall<
    (init_value: boolean, options?: ConstructorTxOptions) => GenericInstantiateSubmittableExtrinsic<ContractApi>,
    Type
  >;
}
