// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericConstructorQuery<ChainApi, Type> {
  /**
   * @param {boolean} init_value
   * @param {ConstructorCallOptions} options
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      init_value: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
