// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {
  Flipped: GenericContractEvent<
    'Flipped',
    {
      /**
       * @indexed: false
       **/
      old_value: boolean;
      /**
       * @indexed: false
       **/
      new_value: boolean;
      /**
       * @indexed: true
       **/
      caller: H160;
    },
    Type
  >;
}
