// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { SolGenericContractApi, SolRegistry } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

export interface FlipperContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends SolGenericContractApi<ChainApi> {
  metadataType: 'sol';
  query: ContractQuery<ChainApi, 'sol'>;
  tx: ContractTx<ChainApi, 'sol'>;
  constructorQuery: ConstructorQuery<ChainApi, 'sol'>;
  events: ContractEvents<ChainApi, 'sol'>;
  constructorTx: ConstructorTx<ChainApi, FlipperContractApi, 'sol'>;

  types: {
    ChainApi: ChainApi;
  };
}
