// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { SolGenericContractApi, SolRegistry } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

export interface FlipperContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends SolGenericContractApi<Rv, ChainApi> {
  metadataType: 'sol';
  query: ContractQuery<ChainApi[Rv], 'sol'>;
  tx: ContractTx<ChainApi[Rv], 'sol'>;
  constructorQuery: ConstructorQuery<ChainApi[Rv], 'sol'>;
  events: ContractEvents<ChainApi[Rv], 'sol'>;
  constructorTx: ConstructorTx<ChainApi[Rv], FlipperContractApi, 'sol'>;

  types: {
    ChainApi: ChainApi[Rv];
  };
}
