// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * @param {ContractCallOptions} options
   **/
  flip: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  get: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;
}
