// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * @param {ContractCallOptions} options
   **/
  flip: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * @param {ContractCallOptions} options
   **/
  get: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>,
    Type
  >;
}
