// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType> extends GenericContractTx<
  ChainApi,
  Type
> {
  /**
   * @param {ContractTxOptions} options
   **/
  flip: GenericContractTxCall<ChainApi, (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>, Type>;
}
