// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Hash, Result } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { FlipperFlipperError, InkPrimitivesLangError } from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * Flips the current value, value based on seed.
   *
   * @param {Hash} seed
   * @param {ContractCallOptions} options
   *
   * @selector 0x847d0968
   **/
  flipWithSeed: GenericContractQueryCall<
    (
      seed: Hash,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<boolean, FlipperFlipperError>, ContractCallResult>>,
    Type
  >;

  /**
   * Flips the current value of the Flipper's boolean.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x633aa551
   **/
  flip: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;

  /**
   * Returns the current value of the Flipper's boolean.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2f865bd9
   **/
  get: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;
}
