// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   * Creates a new greeter contract initialized with the given value.
   *
   * @param {string} initValue
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      initValue: string,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;

  /**
   * Creates a new greeter contract initialized to 'Hello ink!'.
   *
   * @param {ConstructorCallOptions} options
   *
   * @selector 0xed4b9d1b
   **/
  default: GenericConstructorQueryCall<
    (options?: ConstructorCallOptions) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
