// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<Type extends MetadataType> extends GenericContractTx<Type> {
  /**
   * Sets `message` to the given value.
   *
   * @param {string} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x1fe7426f
   **/
  setMessage: GenericContractTxCall<
    (newValue: string, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;
}
