// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Flipper } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: FlipperV5ContractApi
 * @contractName: flipper
 * @contractVersion: 5.0.0
 * @authors: Parity Technologies <admin@parity.io>
 * @language: ink! 5.0.0
 **/
export interface FlipperV5ContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<ChainApi, 'ink'>;
  tx: ContractTx<ChainApi, 'ink'>;
  constructorQuery: ConstructorQuery<ChainApi, 'ink'>;
  constructorTx: ConstructorTx<ChainApi, FlipperV5ContractApi, 'ink'>;
  events: ContractEvents<ChainApi, 'ink'>;
  storage: {
    root(): Promise<Flipper>;
    lazy(): WithLazyStorage<Flipper>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Flipper;
    LazyStorage: WithLazyStorage<Flipper>;
    LangError: InkPrimitivesLangError;
  };
}
