name: Create Typink Tests

on:
  push:
  workflow_dispatch:
  merge_group:

jobs:
  create-typink-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        wallet: ['Default', 'SubConnect V2', 'Talisman Connect']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - name: Create and build app with create-typink (${{ matrix.wallet }})
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          cd ..
          node ./typink/packages/create-typink/dist/bin/create-typink.mjs \
            --no-git -n typink-app-${{ matrix.wallet }} -t default -p greeter \
            -N "Pop Testnet" -N "Aleph Zero Testnet" -w "${{ matrix.wallet }}"
          ls -la
          cd ./typink-app-${{ matrix.wallet }}
          ls -la
          yarn build
