# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Demo Build Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  merge_group:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn workspace demo-general build
    - run: yarn workspace demo-inkv5 build
    - run: yarn workspace demo-inkv6 build
    - run: yarn workspace demo-subconnect build
    - run: yarn workspace demo-lunokit build
